/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./resources/js/components/ActionMessage.vue')['default']
    ActionSection: typeof import('./resources/js/components/ActionSection.vue')['default']
    AddAuthenticatorAppDialog: typeof import('./resources/js/components/dialogs/AddAuthenticatorAppDialog.vue')['default']
    AddEditAddressDialog: typeof import('./resources/js/components/dialogs/AddEditAddressDialog.vue')['default']
    AddEditPermissionDialog: typeof import('./resources/js/components/dialogs/AddEditPermissionDialog.vue')['default']
    AddEditRoleDialog: typeof import('./resources/js/components/dialogs/AddEditRoleDialog.vue')['default']
    AddPaymentMethodDialog: typeof import('./resources/js/components/dialogs/AddPaymentMethodDialog.vue')['default']
    ApplicationLogo: typeof import('./resources/js/components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./resources/js/components/ApplicationMark.vue')['default']
    AppLoadingIndicator: typeof import('./resources/js/components/AppLoadingIndicator.vue')['default']
    AppPricing: typeof import('./resources/js/components/AppPricing.vue')['default']
    AppSearchHeader: typeof import('./resources/js/components/AppSearchHeader.vue')['default']
    AuthenticationCard: typeof import('./resources/js/components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./resources/js/components/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./resources/js/components/Banner.vue')['default']
    CardAddEditDialog: typeof import('./resources/js/components/dialogs/CardAddEditDialog.vue')['default']
    Checkbox: typeof import('./resources/js/components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./resources/js/components/ConfirmationModal.vue')['default']
    ConfirmDialog: typeof import('./resources/js/components/dialogs/ConfirmDialog.vue')['default']
    ConfirmsPassword: typeof import('./resources/js/components/ConfirmsPassword.vue')['default']
    CreateAppDialog: typeof import('./resources/js/components/dialogs/CreateAppDialog.vue')['default']
    DangerButton: typeof import('./resources/js/components/DangerButton.vue')['default']
    DialogModal: typeof import('./resources/js/components/DialogModal.vue')['default']
    Dropdown: typeof import('./resources/js/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/components/DropdownLink.vue')['default']
    EnableOneTimePasswordDialog: typeof import('./resources/js/components/dialogs/EnableOneTimePasswordDialog.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    FormSection: typeof import('./resources/js/components/FormSection.vue')['default']
    InputError: typeof import('./resources/js/components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/components/NavLink.vue')['default']
    PaymentProvidersDialog: typeof import('./resources/js/components/dialogs/PaymentProvidersDialog.vue')['default']
    PricingPlanDialog: typeof import('./resources/js/components/dialogs/PricingPlanDialog.vue')['default']
    PrimaryButton: typeof import('./resources/js/components/PrimaryButton.vue')['default']
    ReferAndEarnDialog: typeof import('./resources/js/components/dialogs/ReferAndEarnDialog.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/components/ResponsiveNavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./resources/js/components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./resources/js/components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./resources/js/components/SectionTitle.vue')['default']
    ShareProjectDialog: typeof import('./resources/js/components/dialogs/ShareProjectDialog.vue')['default']
    TextInput: typeof import('./resources/js/components/TextInput.vue')['default']
    TwoFactorAuthDialog: typeof import('./resources/js/components/dialogs/TwoFactorAuthDialog.vue')['default']
    UserInfoEditDialog: typeof import('./resources/js/components/dialogs/UserInfoEditDialog.vue')['default']
    UserUpgradePlanDialog: typeof import('./resources/js/components/dialogs/UserUpgradePlanDialog.vue')['default']
    Welcome: typeof import('./resources/js/components/Welcome.vue')['default']
  }
}
